# Generated by Django 2.0.6 on 2018-11-27 13:43

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields
from swida.settings import common as app_common_settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(app_common_settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=7)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exports_where_creator', to=app_common_settings.AUTH_USER_MODEL)),
                ('items', gm2m.fields.GM2MField('invoicing.Invoice', 'board.Task', 'board.Inquiry', 'board.Announcement', 'chronicle.Event', 'directory.Company', 'directory.Carrier', 'directory.Activity', 'helpdesk.Article', 'logistics.Offer', 'logistics.Order', 'logistics.Option', 'logistics.ShippingOrder', related_name='exports_where_item', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
                ('recipients', models.ManyToManyField(related_name='exports_where_recipient', to=app_common_settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'export',
                'verbose_name_plural': 'exports',
                'ordering': ('created',),
                'default_permissions': ('list', 'view', 'add', 'change', 'delete'),
            },
        ),
    ]
