# Generated by Django 2.0.6 on 2019-01-13 23:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0004_auto_20181229_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None),
        ),
    ]
