# Generated by Django 2.0.6 on 2019-02-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0006_set_export_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
