# Generated by Django 2.0.6 on 2019-02-09 20:43
from bulk_update.helper import bulk_update
from django.db import migrations
from swida.utils import HideableProgressBar

from outputs.models import Export
from swida.migration_helpers import RunPython


def set_double_underscores_to_dots(*args,**kwargs):
    print('Replacing export fields double underscores with dots')
    exports_with_fields = Export.objects.exclude(fields=[]).defer('context', 'query_string', 'status')

    with HideableProgressBar(max_value=exports_with_fields.count()) as progress:
        index = 0

        for export in exports_with_fields:
            fields = ','.join(export.fields)
            fields = fields.replace('__', '.')
            export.fields = fields.split(',')

        index += 1
        progress.update(index)

        print('Updating export fields')
        bulk_update(exports_with_fields, update_fields=['fields'])


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0007_auto_20190202_1122'),
    ]

    operations = [
        RunPython(set_double_underscores_to_dots)
    ]
