# Generated by Django 2.0.6 on 2019-02-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0008_replace_double_underscores_with_dots'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='context',
            field=models.CharField(default='LIST', max_length=10),
            preserve_default=False,
        ),
    ]
