# Generated by Django 2.0.6 on 2019-02-23 00:22
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.db.models import Q

from swida.core.logistics.models import Order
from outputs.models import Export
from swida.migration_helpers import RunPython


def unset_fields_of_statistics_exports(*args, **kwargs):
    print('Unsetting export fields of statistics exports')

    # statistics orders export fields
    dot_fields = ['order_number', 'created', 'client.name', 'price', 'profit', 'client.name', 'client.reg_id', 'client.tax_id', 'client.vat_id', 'client.payment_term', 'turnover', 'profit']
    underscore_fields = ['order_number', 'created', 'client__name', 'price', 'profit', 'client__name', 'client__reg_id', 'client__tax_id', 'client__vat_id', 'client__payment_term', 'turnover', 'profit']

    # update exports slected by matching fields
    Export.objects.filter(
        Q(content_type=ContentType.objects.get_for_model(Order, for_concrete_model=False)),
        Q(fields=dot_fields) | Q(fields=underscore_fields)
    ).update(fields=[], context=Export.CONTEXT_STATISTICS)


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0009_export_context'),
    ]

    operations = [
        RunPython(unset_fields_of_statistics_exports)
    ]
