# Generated by Django 2.1.7 on 2019-04-04 13:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0010_unset_statistics_export_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='query_string',
            field=models.TextField(blank=True, default=''),
        ),
    ]
