# Generated by Django 3.1.14 on 2023-01-25 11:52

import django
from django.db import migrations, models


def get_check_constraint_kwargs(condition):
    """Return kwargs for CheckConstraint compatible with Django 4.2 and 5.0+"""
    # Django 4.2 and earlier use 'condition', Django 5.0+ use 'check'
    if django.VERSION > (5, 0):
        return {'condition': condition}
    return {'check': condition}


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0011_reformat_export_fields_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='cron_string',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddConstraint(
            model_name='scheduler',
            constraint=models.CheckConstraint(
                **get_check_constraint_kwargs(
                    models.Q(('cron_string', ''), models.Q(_negated=True, routine='CUSTOM'), _connector='OR')
                ),
                name='custom_cron_string'
            ),
        )
    ]
