# Generated by Django 2.1.7 on 2019-04-04 13:45
from bulk_update.helper import bulk_update
from django.db import migrations
from django.http import QueryDict
from swida.utils import HideableProgressBar

from outputs.models import Export
from swida.migration_helpers import RunPython


def get_query_string(params):
    back_url = params.get('back_url')

    if back_url is None:
        # statistics exports doesnt have back_url parameter
        query_dict = QueryDict('', mutable=True)
        query_dict.update(params)
        return query_dict.urlencode()

    try:
        # find index of back_url where params start
        index = back_url.index('/?') + 2
    except ValueError:
        # back_url without any filter applied
        return ''

    return back_url[index:]


def set_query_string(*args, **kwargs):
    exports = Export.objects.all().defer('status')

    print('Updating export query strings')

    with HideableProgressBar(max_value=exports.count()) as progress:
        index = 0

        for export in exports:
            export.query_string = get_query_string(export.params)
            index += 1
            progress.update(index)

        bulk_update(exports, update_fields=['query_string'])


def unset_query_string(*arg, **kwargs):
    Export.objects.all().update(query_string='').defer('status')


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0011_export_query_string'),
    ]

    operations = [
        RunPython(set_query_string, unset_query_string)
    ]
