# Generated by Django 2.1.10 on 2019-08-21 11:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from swida.settings import common as app_common_settings


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(app_common_settings.AUTH_USER_MODEL),
        ('outputs', '0013_remove_export_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=7)),
                ('context', models.CharField(max_length=10)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('query_string', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('routine', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduler_where_creator', to=app_common_settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='scheduler_where_recipient', to=app_common_settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scheduler',
                'verbose_name_plural': 'schedulers',
                'ordering': ('created',),
                'default_permissions': ('list', 'view', 'add', 'change', 'delete'),
            },
        ),
        migrations.AlterField(
            model_name='export',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_where_creator', to=app_common_settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='export',
            name='recipients',
            field=models.ManyToManyField(related_name='export_where_recipient', to=app_common_settings.AUTH_USER_MODEL),
        ),
    ]
