# Generated by Django 3.1.14 on 2023-02-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0014_local_timezone_reschedule_schedulers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='cron_string',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
