# Generated by Django 2.1.10 on 2019-08-21 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0014_auto_20190821_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='executions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=list, size=None),
        ),
    ]
