# Generated by Django 4.2.3 on 2023-07-15 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('outputs', '0015_auto_20230206_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_where_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='export',
            name='items',
            field=gm2m.fields.GM2MField('invoicing.Invoice', 'accounts.Team', 'board.Task', 'board.Inquiry', 'board.Announcement', 'chronicle.Event', 'directory.Company', 'directory.Carrier', 'directory.Activity', 'helpdesk.Article', 'logistics.Offer', 'logistics.Order', 'logistics.Option', 'logistics.ShippingOrder', related_name='exports_where_item', through_fields=['gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk']),
        ),
        migrations.AlterField(
            model_name='export',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_where_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_where_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_where_recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
