# Generated by Django 2.1.10 on 2019-08-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0016_scheduler_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=2),
        ),
    ]
