# Generated by Django 2.1.10 on 2020-01-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0017_scheduler_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='status',
            field=models.CharField(default='FINISHED', max_length=10),
            preserve_default=False,
        ),
    ]
