# Generated by Django 4.2.3 on 2023-08-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0017_export_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
