# Generated by Django 2.1.10 on 2020-01-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0018_export_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
