# Generated by Django 4.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0019_change_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='output_type',
            field=models.CharField(
                verbose_name='output type',
                choices=[('FILE', 'file'), ('STREAM', 'stream')],
                max_length=6,
                default='FILE',
            ),
        ),
        migrations.CreateModel(
            name='ExportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('SUCCESS', 'success'), ('FAILURE', 'failure')], max_length=7, blank=True, verbose_name='result')),
                ('detail', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='outputs.export', verbose_name='export')),
            ],
            options={
                'verbose_name': 'export item',
                'verbose_name_plural': 'export items',
                'ordering': ('created',),
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddIndex(
            model_name='exportitem',
            index=models.Index(fields=['content_type', 'object_id'], name='outputs_exportitem_content_type_object_id_idx'),
        ),
        migrations.AddIndex(
            model_name='exportitem',
            index=models.Index(fields=['export', 'result'], name='outputs_exportitem_export_result_idx'),
        ),
        migrations.AddIndex(
            model_name='exportitem',
            index=models.Index(fields=['export', 'created'], name='outputs_exportitem_export_created_idx'),
        ),
    ]

