# Generated by Django 4.2.8

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0021_migrate_items_to_exportitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='items',
        ),
    ]

